version: '3'

services:
  common_server:
    image: ubuntu
    ports:
      - 4444:4444
    command: >
      bash -c '
      apt update && apt install netcat -y && 
      while true; do echo -e "HTTP/1.1 200 OK\n\npong" | nc -k -l -p 4444 -q 1; done'
    networks:
      - my_network
  
  project_a:
    image: ubuntu
    depends_on: 
      - common_server
    networks:
      - my_network
    command: >
      bash -c '
      apt update && apt install curl -y && 
      while true; do echo "Calling the container";  echo "AAAAAAAA"; curl common_server:4444; sleep 10; done'
networks:
  my_network:
    driver: bridge
